import { strToU8 } from "fflate";
import { text, type AssetPack } from "./common";

/**
 * Cocos Creator 3.x exporter: files are pre-arranged in the project's assets/
 * layout (resources/pixelstage/ + scripts/), so importing is one folder copy.
 * The runtime component rebuilds the scene from scene.json at Play time.
 * Cocos is right-handed y-up like three.js, so placements carry over 1:1.
 */
export function cocosFiles(pack: AssetPack): Record<string, Uint8Array> {
  const files: Record<string, Uint8Array> = {};
  for (const [path, bytes] of Object.entries(pack.files)) {
    files[path.replace(/^assets\//, "assets/resources/pixelstage/")] = bytes;
  }
  files["assets/resources/pixelstage/scene.json"] = strToU8(JSON.stringify(pack.scene, null, 2));
  files["assets/scripts/PixelStageScene.ts"] = text(COCOS_SCRIPT);
  files["README-cocos.txt"] = text(COCOS_README);
  return files;
}

const COCOS_README = `PixelStage → Cocos Creator 3.x
==============================

Import steps (one copy)
-----------------------
1. Copy the CONTENTS of this package's assets/ folder into your Cocos
   Creator project's assets/ folder. You should end up with:
     assets/resources/pixelstage/scene.json  (+ all layer PNGs)
     assets/scripts/PixelStageScene.ts
2. In your scene, create an empty node, add the PixelStageScene component
   to it, and press Play — layers, camera, fog and sun rebuild themselves.

Notes
-----
- 1 px = 1 world unit. Scale the root node if needed.
- Textures are loaded with nearest filtering for crisp pixels.
- Ground layers pivot at their near edge and recede toward the horizon.
- Layers flagged "lit" use builtin-standard materials; unlit layers use
  builtin-unlit (sky, glow overlays).
- Bloom / DOF / grain are PixelStage editor post effects — recreate with
  Cocos post-process if needed.
- If a layer appears upside-down, flip its v coordinate in PixelStageScene.ts
  (see the 'uvs' line) — texture Y conventions differ between pipelines.
`;

const COCOS_SCRIPT = `// PixelStage scene loader — generated by PixelStage.
// Attach to an empty node. Expects assets/resources/pixelstage/{scene.json, *.png}.
import {
  _decorator, Component, Node, JsonAsset, Texture2D, MeshRenderer, Material,
  Camera, DirectionalLight, resources, utils, director, Vec3, Color, Quat,
} from 'cc';
const { ccclass } = _decorator;

interface PSVec3 { x: number; y: number; z: number }
interface PSLayer {
  name: string; src: string; offsetX: number; offsetY: number; depth: number;
  scale: number; orientation: string; lit: boolean; visible: boolean;
  opacity: number; flipX: boolean; flipY: boolean; rotation: number;
}
interface PSScene {
  name: string; canvas: { width: number; height: number };
  camera: { position: PSVec3; target: PSVec3; fov: number };
  effects: {
    fog: { enabled: boolean; color: string; near: number; far: number };
    sun: { color: string; intensity: number; azimuth: number; elevation: number };
  };
  layers: PSLayer[];
}

@ccclass('PixelStageScene')
export class PixelStageScene extends Component {
  start() {
    resources.load('pixelstage/scene', JsonAsset, (err, asset) => {
      if (err || !asset || !asset.json) { console.error('PixelStage: scene.json not found', err); return; }
      this.build(asset.json as unknown as PSScene);
    });
  }

  private build(scene: PSScene) {
    const H = scene.canvas.height;
    for (const l of scene.layers) {
      const file = l.src.replace(/^assets\\//, '').replace(/\\.png$/, '');
      resources.load('pixelstage/' + file + '/texture', Texture2D, (err, tex) => {
        if (err || !tex) { console.warn('PixelStage: missing texture', file); return; }
        this.addLayer(scene, l, tex, H);
      });
    }

    // Camera
    let cam = this.node.scene.getComponentInChildren(Camera);
    if (!cam) {
      const camNode = new Node('PixelStageCamera');
      this.node.scene.addChild(camNode);
      cam = camNode.addComponent(Camera);
    }
    cam.node.setPosition(scene.camera.position.x, H - scene.camera.position.y, scene.camera.position.z);
    cam.node.lookAt(new Vec3(scene.camera.target.x, H - scene.camera.target.y, -scene.camera.target.z));
    cam.fov = scene.camera.fov;
    cam.far = 20000;

    // Fog
    const globals = director.getScene()!.globals;
    if (scene.effects.fog.enabled) {
      globals.fog.enabled = true;
      globals.fog.fogStart = scene.effects.fog.near;
      globals.fog.fogEnd = scene.effects.fog.far;
      Color.fromHEX(globals.fog.fogColor, scene.effects.fog.color);
    }

    // Sun
    const sun = this.node.scene.getComponentInChildren(DirectionalLight);
    if (sun) {
      const el = scene.effects.sun.elevation;
      const az = scene.effects.sun.azimuth;
      sun.node.setRotationFromEuler(-el, -az, 0);
      Color.fromHEX(sun.color, scene.effects.sun.color);
      sun.illuminance = scene.effects.sun.intensity * 20000;
    }
  }

  private addLayer(scene: PSScene, l: PSLayer, tex: Texture2D, H: number) {
    const w = tex.width * l.scale;
    const h = tex.height * l.scale;
    const ground = l.orientation === 'ground';

    const node = new Node(l.name);
    this.node.addChild(node);
    if (ground) {
      node.setPosition(l.offsetX + w / 2, H - l.offsetY, -l.depth);
      node.setRotationFromEuler(90, 0, l.rotation);
    } else {
      node.setPosition(l.offsetX + w / 2, H - l.offsetY - h / 2, -l.depth);
      node.setRotationFromEuler(0, 0, l.rotation);
    }
    node.setScale(l.flipX ? -1 : 1, l.flipY ? -1 : 1, 1);
    node.active = l.visible;

    const meshNode = new Node(l.name + '_Mesh');
    node.addChild(meshNode);
    if (ground) meshNode.setPosition(0, -h / 2, 0);

    // unit quad, top-left uv origin (flip here if your pipeline shows it mirrored)
    const mesh = utils.createMesh({
      positions: [-0.5, -0.5, 0, 0.5, -0.5, 0, -0.5, 0.5, 0, 0.5, 0.5, 0],
      normals: [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1],
      uvs: [0, 1, 1, 1, 0, 0, 1, 0],
      indices: [0, 1, 2, 2, 1, 3],
      minPos: new Vec3(-0.5, -0.5, 0),
      maxPos: new Vec3(0.5, 0.5, 0),
    });
    meshNode.setScale(w, h, 1);

    const mr = meshNode.addComponent(MeshRenderer);
    mr.mesh = mesh;
    const mat = new Material();
    const transparent = l.opacity < 0.999;
    mat.initialize({
      effectName: l.lit ? 'builtin-standard' : 'builtin-unlit',
      technique: transparent ? 1 : 0,
      defines: { USE_TEXTURE: true, USE_ALPHA_TEST: !transparent },
    });
    mat.setProperty('mainTexture', tex);
    if (transparent) mat.setProperty('mainColor', new Color(255, 255, 255, Math.round(l.opacity * 255)));
    mr.setMaterial(mat, 0);
  }
}
`;
