import { baseFiles, text, type AssetPack } from "./common";

/**
 * Unity exporter: Unity scene YAML needs GUID-matched .meta files to be
 * reliable, so instead we generate a C# editor script that rebuilds the
 * scene from scene.json at import time (menu: Tools > PixelStage > Import).
 * Coordinates are mapped from three-space (y up, camera at +z) to Unity's
 * left-handed space (camera looking +z) via z → -z.
 */
export function unityFiles(pack: AssetPack): Record<string, Uint8Array> {
  return {
    ...baseFiles(pack),
    "Editor/PixelStageImporter.cs": text(UNITY_IMPORTER_CS),
    "README-unity.txt": text(UNITY_README),
  };
}

const UNITY_README = `PixelStage → Unity
================

Import steps
------------
1. Extract this zip anywhere inside your project's Assets folder
   (e.g. Assets/PixelStage/). scene.json, assets/ and Editor/ should
   keep their relative layout.
2. Wait for Unity to compile the editor script.
3. Menu: Tools > PixelStage > Import Scene.json — pick the scene.json
   from this package.
4. A GameObject tree with all layers, a camera, fog and a sun light is
   created in the open scene.

Notes
-----
- 1 px = 1 unit. Scale the root if needed.
- Layers use Unlit/Transparent (or Cutout) materials with Point filtering,
  so pixels stay crisp and lighting is flat by default. Re-create lit
  shading with URP/HDRP materials if your pipeline needs it — the "lit"
  flag per layer is in scene.json.
- Ground layers pivot at their near edge (child quad offset), receding
  toward the horizon like in the PixelStage editor.
- Bloom / depth of field / grain are editor post effects — add them with
  a Volume (URP) or Post Processing stack if you want the full HD-2D look.
- Double-check in-plane rotation of ground layers; Unity's left-handed
  axes can read as mirrored in some framings.
`;

const UNITY_IMPORTER_CS = `// PixelStage scene importer — generated by PixelStage.
// Menu: Tools > PixelStage > Import Scene.json
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class PixelStageImporter
{
    [Serializable] public class Vec3 { public float x, y, z; }
    [Serializable] public class Canvas { public int width, height; }
    [Serializable] public class CameraData { public Vec3 position; public Vec3 target; public float fov; }
    [Serializable] public class Fog { public bool enabled; public string color; public float near, far; }
    [Serializable] public class Ambient { public string color; public float intensity; }
    [Serializable] public class Sun { public string color; public float intensity, azimuth, elevation; }
    [Serializable] public class Effects { public Fog fog; public Ambient ambient; public Sun sun; }
    [Serializable] public class Layer
    {
        public string name, src, orientation;
        public float offsetX, offsetY, depth, scale, opacity, rotation;
        public bool lit, visible, flipX, flipY;
    }
    [Serializable] public class SceneFile
    {
        public string name;
        public Canvas canvas;
        public CameraData camera;
        public Effects effects;
        public List<Layer> layers;
    }

    [MenuItem("Tools/PixelStage/Import Scene.json")]
    public static void Import()
    {
        string path = EditorUtility.OpenFilePanel("Select PixelStage scene.json", Application.dataPath, "json");
        if (string.IsNullOrEmpty(path)) return;
        var scene = JsonUtility.FromJson<SceneFile>(File.ReadAllText(path));
        string dir = Path.GetDirectoryName(path).Replace('\\\\', '/');
        float H = scene.canvas.height;

        var root = new GameObject(string.IsNullOrEmpty(scene.name) ? "PixelStageScene" : scene.name);
        Undo.RegisterCreatedObjectUndo(root, "Import PixelStage scene");

        foreach (var l in scene.layers)
        {
            var tex = LoadTexture(dir, l.src);
            float w = (tex != null ? tex.width : scene.canvas.width) * l.scale;
            float h = (tex != null ? tex.height : scene.canvas.height) * l.scale;
            bool ground = l.orientation == "ground";

            var node = new GameObject(l.name);
            node.transform.SetParent(root.transform, false);
            if (ground)
            {
                node.transform.localPosition = new Vector3(l.offsetX + w / 2f, H - l.offsetY, l.depth);
                node.transform.localRotation = Quaternion.Euler(90f, 0f, l.rotation);
            }
            else
            {
                node.transform.localPosition = new Vector3(l.offsetX + w / 2f, H - l.offsetY - h / 2f, l.depth);
                node.transform.localRotation = Quaternion.Euler(0f, 0f, l.rotation);
            }

            var quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
            UnityEngine.Object.DestroyImmediate(quad.GetComponent<Collider>());
            quad.name = l.name + "_Mesh";
            quad.transform.SetParent(node.transform, false);
            if (ground) quad.transform.localPosition = new Vector3(0f, -h / 2f, 0f);
            quad.transform.localScale = new Vector3(w * (l.flipX ? -1f : 1f), h * (l.flipY ? -1f : 1f), 1f);

            var shader = Shader.Find(l.opacity < 0.999f ? "Unlit/Transparent" : "Unlit/Transparent Cutout");
            var mat = new Material(shader) { name = l.name + "_Mat" };
            if (tex != null) mat.mainTexture = tex;
            if (l.opacity < 0.999f) mat.color = new Color(1f, 1f, 1f, l.opacity);
            quad.GetComponent<MeshRenderer>().sharedMaterial = mat;

            node.SetActive(l.visible);
        }

        // Camera — three.js space (y up, +z toward viewer) → Unity (y up, +z away): z flips.
        var camGo = new GameObject("PixelStageCamera");
        camGo.transform.SetParent(root.transform, false);
        var cam = camGo.AddComponent<Camera>();
        cam.fieldOfView = scene.camera.fov;
        cam.farClipPlane = 20000f;
        Vector3 pos = new Vector3(scene.camera.position.x, H - scene.camera.position.y, -scene.camera.position.z);
        Vector3 tgt = new Vector3(scene.camera.target.x, H - scene.camera.target.y, scene.camera.target.z);
        camGo.transform.localPosition = pos;
        camGo.transform.localRotation = Quaternion.LookRotation(tgt - pos, Vector3.up);
        camGo.tag = "MainCamera";

        // Fog + ambient + sun
        if (scene.effects != null && scene.effects.fog != null && scene.effects.fog.enabled)
        {
            RenderSettings.fog = true;
            RenderSettings.fogMode = FogMode.Linear;
            RenderSettings.fogStartDistance = scene.effects.fog.near;
            RenderSettings.fogEndDistance = scene.effects.fog.far;
            Color fc;
            if (ColorUtility.TryParseHtmlString(scene.effects.fog.color, out fc)) RenderSettings.fogColor = fc;
        }
        if (scene.effects != null && scene.effects.ambient != null)
        {
            Color ac;
            if (ColorUtility.TryParseHtmlString(scene.effects.ambient.color, out ac))
            {
                RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
                RenderSettings.ambientLight = ac * Mathf.Clamp01(scene.effects.ambient.intensity);
            }
        }
        if (scene.effects != null && scene.effects.sun != null)
        {
            float az = scene.effects.sun.azimuth * Mathf.Deg2Rad;
            float el = scene.effects.sun.elevation * Mathf.Deg2Rad;
            var sunGo = new GameObject("Sun");
            sunGo.transform.SetParent(root.transform, false);
            var sun = sunGo.AddComponent<Light>();
            sun.type = LightType.Directional;
            sun.intensity = scene.effects.sun.intensity;
            Color sc;
            if (ColorUtility.TryParseHtmlString(scene.effects.sun.color, out sc)) sun.color = sc;
            Vector3 sunDir = new Vector3(Mathf.Sin(az) * Mathf.Cos(el), -Mathf.Sin(el), Mathf.Cos(az) * Mathf.Cos(el));
            sunGo.transform.rotation = Quaternion.LookRotation(sunDir, Vector3.up);
        }

        Selection.activeGameObject = root;
        Debug.Log("PixelStage: imported " + scene.layers.Count + " layers.");
    }

    static Texture2D LoadTexture(string sceneDir, string src)
    {
        if (string.IsNullOrEmpty(src) || src.StartsWith("data:")) return null;
        string full = Path.GetFullPath(Path.Combine(sceneDir, src)).Replace('\\\\', '/');
        int i = full.IndexOf("/Assets/", StringComparison.Ordinal);
        if (i < 0)
        {
            Debug.LogWarning("PixelStage: texture is outside the project's Assets folder: " + full);
            return null;
        }
        string assetPath = full.Substring(i + 1);
        var importer = AssetImporter.GetAtPath(assetPath) as TextureImporter;
        if (importer != null)
        {
            importer.filterMode = FilterMode.Point;
            importer.mipmapEnabled = false;
            importer.alphaIsTransparency = true;
            importer.SaveAndReimport();
        }
        return AssetDatabase.LoadAssetAtPath<Texture2D>(assetPath);
    }
}
`;
